export const PUSH_BOARD = 'PUSH_BOARD'

// CRUD
export const CREATE_BOARD_REQUEST = 'CREATE_BOARD_REQUEST'
export const UPDATE_BOARD_REQUEST = 'UPDATE_BOARD_REQUEST'
export const REMOVE_BOARD_REQUEST = 'REMOVE_BOARD_REQUEST'
export const QUIT_BOARD_REQUEST = 'QUIT_BOARD_REQUEST'

export const RESET_STATE_BOARD = 'RESET_STATE_BOARD'

export const SELECT_BOARD = 'SELECT_BOARD'

export const ADD_STAGE_BOARD_REQUEST = 'ADD_STAGE_BOARD_REQUEST'
export const RENAME_STAGE_BOARD_REQUEST = 'RENAME_STAGE_BOARD_REQUEST'
