export const PUSH_COLOR = 'PUSH_COLOR'
export const PUSH_MYCOLOR = 'PUSH_MYCOLOR'

export const SELECT_COLOR = 'SELECT_COLOR'
export const CREATE_COLOR_REQUEST = 'CREATE_COLOR_REQUEST'
export const UPDATE_COLOR_REQUEST = 'UPDATE_COLOR_REQUEST'
export const REMOVE_COLOR_REQUEST = 'REMOVE_COLOR_REQUEST'
