export const PUSH_DEPARTMENT = 'PUSH_DEPARTMENT'
export const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT'

export const CREATE_DEPARTMENT_REQUEST = 'CREATE_DEPARTMENT_REQUEST'
export const UPDATE_DEPARTMENT_REQUEST = 'UPDATE_DEPARTMENT_REQUEST'
export const REMOVE_DEPARTMENT_REQUEST = 'REMOVE_DEPARTMENT_REQUEST'
