export const PUSH_EMPLOYEE = 'PUSH_EMPLOYEE'
export const PUSH_EMPLOYEE_BY_EMAIL = 'PUSH_EMPLOYEE_BY_EMAIL'
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE'

export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST'
export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST'
export const REMOVE_EMPLOYEE_REQUEST = 'REMOVE_EMPLOYEE_REQUEST'
