export const PUSH_EMPLOYEE = 'PUSH_EMPLOYEE'
export const PUSH_EMPLOYEE_BY_EMAIL = 'PUSH_EMPLOYEE_BY_EMAIL'
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE'

export const CREATE_EMPLOYEE_REQUEST = 'CREATE_COLOR_REQUEST'
export const UPDATE_EMPLOYEE_REQUEST = 'CREATE_COLOR_REQUEST'
export const REMOVE_EMPLOYEE_REQUEST = 'CREATE_COLOR_REQUEST'
