export const CREATE_INSPECTOR_TASK = 'CREATE_INSPECTOR_TASK'
export const CREATE_OR_UPDATE_INSPECTOR_USER = 'CREATE_OR_UPDATE_INSPECTOR_USER'
export const ANSWER_INSPECTOR_TASK = 'ANSWER_INSPECTOR_TASK'
