export const NAVIGATOR_REQUEST = 'NAVIGATOR_REQUEST'
export const NAVIGATOR_SUCCESS = 'NAVIGATOR_SUCCESS'
export const NAVIGATOR_ERROR = 'NAVIGATOR_ERROR'
export const PATCH_SETTINGS = 'PATCH_SETTINGS'
export const PATCH_SETTINGS_SUCCESS = 'PATCH_SETTINGS_SUCCESS'
export const RESET_STATE_NAVIGATOR = 'RESET_STATE_NAVIGATOR '

export const NAVIGATOR_PUSH_PROJECT = 'NAVIGATOR_PUSH_PROJECT'
export const NAVIGATOR_REMOVE_PROJECT = 'NAVIGATOR_REMOVE_PROJECT'
