export const PUSH_PROJECT = 'PUSH_PROJECT'

// CRUD
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST'
export const REMOVE_PROJECT_REQUEST = 'REMOVE_PROJECT_REQUEST'
export const QUIT_PROJECT_REQUEST = 'QUIT_PROJECT_REQUEST'
